services:
    # WebRTC 서버
    webrtc-server:
        build: ./webrtc-server
        ports:
            - '8080:8080'
        volumes:
            - ./webrtc-server:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
        restart: unless-stopped
